### ISSUE TITLE
手机发送和接收的消息很久才会在wewechat上显示

### ISSUE THREAD

**Issue by owwlo** [trazyn/weweChat#135]
使用的是1.1.5的64bit的deb版本。

之前一直在用electronic-wechat没有这个问题。

感觉像是后台timer轮询服务器拉消息是这样吗？

**Comment by pcieX** [comment]
Don't send me any emails

    
        
            
                
                    
                        
                    
                    
                        
                            X PCIe
                            
                            
                                
                                    邮箱：pciex7108@gmail.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master
在2018年06月15日 04:50，Weilun Wang 写道： 使用的是1.1.5的64bit的deb版本。
之前一直在用electronic-wechat没有这个问题。
感觉像是后台timer轮询服务器拉消息是这样吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/trazyn/weweChat/issues/135","url":"https://github.com/trazyn/weweChat/issues/135","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/trazyn/weweChat","title":"trazyn/weweChat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/trazyn/weweChat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"手机发送和接收的消息很久才会在wewechat上显示 (#135)"}],"action":{"name":"View Issue","url":"https://github.com/trazyn/weweChat/issues/135"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "手机发送和接收的消息很久才会在wewechat上显示 (#135)",
"sections": [
{
"text": "",
"activityTitle": "**Weilun Wang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@owwlo",
"facts": [
{
"name": "Repository: ",
"value": "trazyn/weweChat"
},
{
"name": "Issue #: ",
"value": 135
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"trazyn/weweChat\",\n\"issueId\": 135,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"trazyn/weweChat\",\n\"issueId\": 135\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/trazyn/weweChat/issues/135"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 346198111\n}"
}
],
"themeColor": "26292E"
}

**Comment by trazyn** [comment]
Close #152
