### ISSUE TITLE
聊天框注入问题

### ISSUE THREAD

**Issue by T1melessWish** [trazyn/weweChat#24]
你好，发现一个问题：
聊天框可以通过输入HTML，js等代码进行客户端注入

**Comment by trazyn** [comment]
只能自己注入自己，并没有什么用，直接append html到客户端也是为了以后插件提供可能，到时候就有可能某个插件去注入你了

服务器端返回的都是被处理过的，这个是安全的，看请求就能发现


On August 30, 2017 at 4:40:41 PM, T1melessWish (notifications@github.com)
wrote:

你好，发现一个问题：
聊天框可以通过输入HTML，js等代码进行客户端注入

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/trazyn/weweChat/issues/24>, or mute the thread
