### ISSUE TITLE
Plugin 里的消息备份是干嘛用的

### ISSUE THREAD

**Issue by skychan** [trazyn/weweChat#96]
如题，plugin 里面的message backup，选项，默认是选上的，不能关，不知道是干嘛用的，有来解答一下的吗？

**Comment by trazyn** [comment]
额 目前没有用没法备份

**Comment by pcieX** [comment]
草你妈




    
    
        
            
                
                    
                        
                    
                    
                        
                            X PCIe
                            
                            
                                
                                    邮箱：pciex7108@gmail.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年07月25日 23:43，trazyn 写道： Closed #96.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/trazyn/weweChat","title":"trazyn/weweChat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/trazyn/weweChat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #96."}],"action":{"name":"View Issue","url":"https://github.com/trazyn/weweChat/issues/96#event-1752948969"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/trazyn/weweChat/issues/96#event-1752948969",
"url": "https://github.com/trazyn/weweChat/issues/96#event-1752948969",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [trazyn/weweChat] Plugin 里的消息备份是干嘛用的 (#96)",
"sections": [
{
"text": "",
"activityTitle": "**trazyn**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@trazyn",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/trazyn/weweChat/issues/96#event-1752948969"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 290972698\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by pcieX** [comment]
别老发邮件过来




    
    
        
            
                
                    
                        
                    
                    
                        
                            X PCIe
                            
                            
                                
                                    邮箱：pciex7108@gmail.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年07月25日 23:49，X PCIe 写道： 
草你妈




    
    
        
            
                
                    
                        
                    
                    
                        
                            X PCIe
                            
                            
                                
                                    邮箱：pciex7108@gmail.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年07月25日 23:43，trazyn 写道： Closed #96.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/trazyn/weweChat","title":"trazyn/weweChat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/trazyn/weweChat"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #96."}],"action":{"name":"View Issue","url":"https://github.com/trazyn/weweChat/issues/96#event-1752948969"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/trazyn/weweChat/issues/96#event-1752948969",
"url": "https://github.com/trazyn/weweChat/issues/96#event-1752948969",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [trazyn/weweChat] Plugin 里的消息备份是干嘛用的 (#96)",
"sections": [
{
"text": "",
"activityTitle": "**trazyn**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@trazyn",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/trazyn/weweChat/issues/96#event-1752948969"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 290972698\n}"
}
],
"themeColor": "26292E"
}
]
